CONSOLE_SIZE_X = 128
CONSOLE_SIZE_Y = 40

STATS_PANEL_X = 32
STATS_PANEL_Y = CONSOLE_SIZE_Y

MESSAGE_SIZE_X = CONSOLE_SIZE_X - STATS_PANEL_X
MESSAGE_SIZE_Y = 10

DUNGEON_DISPLAY_WIDTH = CONSOLE_SIZE_X - STATS_PANEL_X
DUNGEON_DISPLAY_HEIGHT = CONSOLE_SIZE_Y - MESSAGE_SIZE_Y